#!/bin/bash
stars=10
timesteps=10
function run_cs257 {
  run=$(./cs257 $stars $timesteps 0)
  var=0
  for x in $run; do 
    #echo $x
    var=$((var+1))
    # Loop 0
    if [ $var -eq 16 ]
      then
        echo Loop 0 $x
        printf $x >> test.csv
        printf , >> test.csv
    fi
    # Loop 1
    if [ $var -eq 21 ]
      then
        echo Loop 1 $x
        printf $x >> test.csv
        printf , >> test.csv
    fi
    # # Loop 2
    if [ $var -eq 26 ]
      then
        echo Loop 2 $x
        printf $x >> test.csv
        printf , >> test.csv
    fi
    # Loop 3
    if [ $var -eq 31 ]
      then
        echo Loop 3 $x
        printf $x >> test.csv
        printf , >> test.csv
    fi
    # Total
    if [ $var -eq 35 ]
      then
        echo Total $x
        printf $x >> test.csv
        printf , >> test.csv
    fi
    # GFLOP/s
    if [ $var -eq 39 ]
      then
        echo GFLOP $x
        printf $x >> test.csv
        printf , >> test.csv
    fi
    # GB/s
    if [ $var -eq 42 ]
      then
        echo GB $x
        printf $x >> test.csv
        printf , >> test.csv
    fi
    # Answer
    if [ $var -eq 45 ]
      then
        echo Answer $x
        printf $x >> test.csv
    fi
  done
}
# Comment out if just want to add stuff to the end.
# printf stars,timesteps,loop0,loop1,loop2,loop3,total,gflop,gb,answer > test.csv
# echo >> test.csv


# count=1

# while [ $count -lt 11 ]; do
#   #run_cs257
#   count=$((count+1))
#   stars=10
#   timesteps=10

#   while [ $stars -lt 10000 ]; do
#     # while [ $timesteps -lt 10000 ]; do
#       echo ---$stars stars----
#       echo ---$timesteps timesteps---
#       # printf $stars >> test.csv
#       #printf , >> test.csv
#       #printf $timesteps >> test.csv
#       #printf , >> test.csv
#       run_cs257
#       let timesteps=timesteps*10
#       #echo >> test.csv
#     # done
#     # timesteps=1
#     let stars=stars*10
#   done 

#   echo >> test.csv

# done

count=1

while [ $count -lt 11 ]; do
  run_cs257
  echo >> test.csv
  count=$((count+1))
done 

# while [ $stars -lt 10000 ]; do
#   while [ $timesteps -lt 10000 ]; do
#     echo ---$stars stars----
#     echo ---$timesteps timesteps---
#     printf $stars >> test.csv
#     printf , >> test.csv
#     printf $timesteps >> test.csv
#     printf , >> test.csv
#     run_cs257
#     let timesteps=timesteps*10
#     echo >> test.csv
#   done
#   timesteps=1
#   let stars=stars*10
# done 
